### ISSUE TITLE
Attributes remain after deleting environment properties

### ISSUE THREAD

**Issue by RobinQuetin** [RafVandelaer/Cairis-web-develop#2]
Tested with: Attackers

When you remove an environment from the list of environment properties, the properties are not removed and remain visible in the panel next to the list.

![image](https://cloud.githubusercontent.com/assets/11588730/8106619/bf18ed4a-103a-11e5-8b57-987928ad62c0.png)

**Comment by RafVandelaer** [comment]
These are now removed when deleting a environment
