### ISSUE TITLE
Improvements in visual design

### ISSUE THREAD

**Issue by RobinQuetin** [RafVandelaer/Cairis-web-develop#3]
This issue is used to address mistakes in the visual design of the UI.

**Comment by RobinQuetin** [comment]
Tested on: Add asset dialog

![image](https://cloud.githubusercontent.com/assets/11588730/8106702/a3842530-103b-11e5-804d-50c42e05e8a0.png)

**Comment by RobinQuetin** [comment]
Tested in: Assets, Threats

Dialog box is placed behind the Options panel, which makes it possible to 'hide' behind the options panel.

![image](https://cloud.githubusercontent.com/assets/11588730/8107268/0e7967b6-1040-11e5-9bc5-521aca4cc7af.png)

**Comment by RafVandelaer** [comment]
Z-index in the Dialog boxes is fixed, as well as the environments in the asset option box.
