### ISSUE TITLE
Empty vulnerability when adding new vulnerability

### ISSUE THREAD

**Issue by RobinQuetin** [RafVandelaer/Cairis-web-develop#5]
Tested in: Vulnerabilities

When adding a new vulnerability, the grid automatically displays a new row even when the new vulnerability is not yet created. When you, for example, close the dialog window and try to add a new one, a second empty row is created.

![image](https://cloud.githubusercontent.com/assets/11588730/8106891/22504b2c-103d-11e5-86b7-95d4085e035c.png)

**Comment by RafVandelaer** [comment]
This line of code is removed. Thanks for noticing
