### ISSUE TITLE
Severity combo box is empty

### ISSUE THREAD

**Issue by RobinQuetin** [RafVandelaer/Cairis-web-develop#6]
Tested in: Vulnerability dialog

The combo box containing the severity levels is empty.

![SeverityComboBox](https://cloud.githubusercontent.com/assets/11588730/8106992/f6d1a9d6-103d-11e5-8a19-6f170510512d.png)

**Comment by RafVandelaer** [comment]
The Ajax call was not executed when adding a new Vulnerability. Fixed...
