### ISSUE TITLE
Add attackers to threat with no environment properties

### ISSUE THREAD

**Issue by RobinQuetin** [RafVandelaer/Cairis-web-develop#7]
Upon trying to add an attacker to a threat without an environment property (selected) the UI displays a message which says that all possible attackers are already added. The message is incorrect and should be more like 'Unable to add attackers without specifying an environment'

A tip: maybe you could hide the properties panel when no environment is selected or added.

**Comment by RafVandelaer** [comment]
The UI now doesn't show this panel when no environment is selected or added
